# The URL the site will be built for
base_url = "https://luzid.app"
title = "Luzid"
description = "Luzid: Solana Development at Light Speed"

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feed = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  { name = "authors" }, # Basic definition: no feed or pagination
]

# Whether to build a search index to be used later on by a JavaScript library
# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting.
# Theme can be customised by setting the `highlight_theme`
# variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Thorsten Lorenz"
github = "https://github.com/thlorenz"
twitter = "https://twitter.com/thlorenz"
ganalytics = ""                          # Google Analytics code

# If running on netlify.app site, set to true
is_netlify = false

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"

# More about site's title
title_separator = "|"                                # set as |, -, _, etc
title_addition = "Solana Development at Light Speed"


# Set date format in blog publish metadata
timeformat = "%Y-%m-%d %H:%M:%S" # e.g. 2021-05-01 09:19:42
timezone = "UTC"

# Edit page on reposity or not
edit_page = false
docs_repo = "https://github.com/luzid-app"
repo_branch = "main"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex" # options: "katex", "mathjax". default is "katex".

## Open Graph + Twitter Cards
[extra.open]
enable = true
# this image will be used as fallback if a page has no image of its own
image = "luzid.png"
twitter_site = "thlorenz"
twitter_creator = "thlorenz"
og_locale = "en_US"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo-luzid.png"
twitter = "https://twitter.com/thlorenz"
linked_in = ""
github = "https://github.com/luzid-app"
section = "blog"                         # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = false

[[extra.menu.social]]
name = "Discord"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path fill="#fff" d="M 19.73 4.87 a 18.2 18.2 0 0 0 -4.6 -1.44 c -0.21 0.4 -0.4 0.8 -0.58 1.21 c -1.69 -0.25 -3.4 -0.25 -5.1 0 c -0.18 -0.41 -0.37 -0.82 -0.59 -1.2 c -1.6 0.27 -3.14 0.75 -4.6 1.43 A 19.04 19.04 0 0 0 0.96 17.7 a 18.43 18.43 0 0 0 5.63 2.87 c 0.46 -0.62 0.86 -1.28 1.2 -1.98 c -0.65 -0.25 -1.29 -0.55 -1.9 -0.92 c 0.17 -0.12 0.32 -0.24 0.47 -0.37 c 3.58 1.7 7.7 1.7 11.28 0 l 0.46 0.37 c -0.6 0.36 -1.25 0.67 -1.9 0.92 c 0.35 0.7 0.75 1.35 1.2 1.98 c 2.03 -0.63 3.94 -1.6 5.64 -2.87 c 0.47 -4.87 -0.78 -9.09 -3.3 -12.83 Z M 8.3 15.12 c -1.1 0 -2 -1.02 -2 -2.27 c 0 -1.24 0.88 -2.26 2 -2.26 s 2.02 1.02 2 2.26 c 0 1.25 -0.89 2.27 -2 2.27 Z m 7.4 0 c -1.1 0 -2 -1.02 -2 -2.27 c 0 -1.24 0.88 -2.26 2 -2.26 s 2.02 1.02 2 2.26 c 0 1.25 -0.88 2.27 -2 2.27 Z"/></svg>'
url = "https://discord.gg/RftFKAN8Q8"
weight = 10

[[extra.menu.social]]
name = "Twitter"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
url = "https://twitter.com/thlorenz"
weight = 10

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/luzid-app"
post = "v0.0.0"
weight = 20

# Footer contents
# [extra.footer]
# info = 'Powered by <a href="https://www.netlify.com/">Netlify</a>, <a href="https://www.getzola.org/">Zola</a>, and <a href="https://github.com/aaranxu/adidoks">AdiDoks</a>'

# [[extra.footer.nav]]
# name = "Privacy"
# url = "/privacy-policy/"
# weight = 10
