#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR/..
COMMIT_HASH=$(git rev-parse --short HEAD)

zola build                                                             && \
cd $DIR/../public                                                      && \
rm -rf .git                                                            && \
git init -b gh-pages                                                   && \
git remote add origin git@github.com:luzid-app/luzid-app.github.io.git && \
git add .                                                              && \
git commit -m "chore: deploy page at ${COMMIT_HASH}"                   && \
git push -f origin gh-pages
